workflows:
    ios-workflow:
      name: iOS Workflow
      environment:
        groups:
          - app_store_credentials
        vars:
          XCODE_PROJECT: "AirPodsFInder.xcodeproj"
          XCODE_SCHEME: "AirPodsFInder"
          A_BUNDLE_ID: "air.pods.headphones"
          APP_STORE_APP_ID: 6744161933
        xcode: latest
      scripts:
        - name: Test echo
          script: |
            echo $APP_STORE_CONNECT_ISSUER_ID
            echo $APP_STORE_CONNECT_KEY_IDENTIFIER
            echo $APP_STORE_CONNECT_PRIVATE_KEY
            echo $CERTIFICATE_PRIVATE_KEY
            defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Fetch signing files
          script: |
            app-store-connect fetch-signing-files $A_BUNDLE_ID --type IOS_APP_STORE --create --verbose
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles --verbose
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
        - name: Upload debug symbols to Firebase Crashlytics
          script: |
            echo "Find build artifacts"
            IFS=$'\n'
            dsymPath=$(find build/ios/xcarchive/* | head -1)
            echo "dsyms expected in:"
            ls -d -- $dsymPath/dSYMs/*
            dsymFile=$(find $dsymPath/dSYMs -name "*.dSYM" | head -1)
            if [[ -z ${dsymFile} ]]
              then
                echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
                exit 1
              else
                echo "Publishing debug symbols in $dsymFile to Firebase Crashlytics"
                echo $dsymFile
                ls -d -- $CM_BUILD_DIR/*
                $HOME/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols \
                  -gsp $CM_BUILD_DIR/$XCODE_SCHEME/GoogleService-Info.plist -p ios $dsymFile
            fi
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY
            key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID
            submit_to_testflight: false
